# Generated by Django 5.1.3 on 2024-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tenants_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
